<?php
const IW_ASSETS_FOLDER = "iassets/";
const IW_DEFINE_FOLDER = "idefine/";
const IW_PANEL_FOLDER = "ipanel/";
const IW_REPOSITORY_FOLDER = "irepository/";
const IW_PANEL_THEME_FOLDER = "iptheme/";
const IW_WEB_THEME_FOLDER = "iwtheme/";
const IW_PANEL_JSON_FOLDER = "ijson/";
const IW_WEB_FOLDER = "iweb/";

const IW_MAIN_ROOT_FROM_PANEL = "../";
const IW_PANEL_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_PANEL_FOLDER;
const IW_WEB_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_WEB_FOLDER;
const IW_ASSETS_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_ASSETS_FOLDER;
const IW_DEFINE_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_DEFINE_FOLDER;
const IW_REPOSITORY_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_REPOSITORY_FOLDER;
const IW_PANEL_THEME_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_PANEL_THEME_FOLDER;
const IW_PANEL_JSON_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_PANEL_JSON_FOLDER;
const IW_WEB_THEME_FROM_PANEL = IW_MAIN_ROOT_FROM_PANEL . IW_WEB_THEME_FOLDER;


